#spring:
#  thymeleaf:
#    cache: false
#    prefix: /WEB-INF/views/
#    suffix: .jsp
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/context?characterEncoding=utf-8&useSSL=false
#    username: root
#    password:
#  resources:
#    static-locations: /WEB-INF/views/